name: Build and publish Docker Image

on:
  workflow_dispatch: # for testing the workflow
    inputs:
      confirm_destory:
        description: 'Type "yes" to confirm deployment'
        required: true
        type: string
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        echo "Logging in to Amazon ECR..."
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Build Docker image
      run: |
        docker build . -t hafiz-quran:latest

    - name: Tag Docker Image
      run: |
        echo "Taggin Docker Image"
        docker tag hafiz-quran:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push the Docker image to ECR 
      run: |
        echo "Pushing Docker image to ECR..."
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest