name: Build and publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build . -t hafiz-quran:latest

    - name: Log in to Amazon ECR
      id: login-ecr
      run: |
        docker build . -t hafiz-quran:latest

    - name: Tag Docker Image
      run: |
        echo "Taggin Docker Image"
        docker tag hafiz-quran:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push the Docker image to ECR 
      run: |
        echo "Pushing Docker image to ECR..."
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest