name: Terraform AWS Production workflow
on:
  push:
    branches: [ T114-Terraform-GitHub-actions-pipeline ]
    # paths: 
    #   - 'terraform/**'

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}


jobs: 
  terraform: 
    name: Terraform
    runs-on: ubuntu-latest

    steps: 
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

     - name: Set up Terraform 
       uses: hashicorp/setup-terraform@v2
       with: 
          terraform_version: "1.5.0"

     - name: Initialize Terraform
       working-directory: ./terraform
       run: terraform init
    
     -  name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

     - name: Terraform Plan
       working-directory: ./terraform 
       run: |
          terraform plan -input=false -out=tfplan

    #  - name: Terraform Apply 
    #    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #    working-directory: ./terraform
    #    run: terraform apply -auto-approve tfplan

        