
name: Publish Docker Image to AWS ECR

on:
  repository_dispatch:
    types: [publish-docker-image]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          echo "Logging in to Amazon ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Tag Docker image
        run: |
          echo "Tagging Docker image..."
          docker tag your-image-name:latest ${{ secrets.ECR_REPOSITORY }}:latest  

      - name: Push Docker image to ECR
        run: |
          echo "Pushing Docker image to ECR..."
          docker push ${{ secrets.ECR_REPOSITORY }}:latest