name: Terraform Destroy Workflow

on:
  workflow_dispatch

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v2
        with: 
          terraform_version: "1.5.0"

      - name: Initialise Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Scale down ECS Service
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve -var="ecs_service_desired_count=0" -target=aws_ecs_service.app_service
    
      - name: Wait for scale down
        run: sleep 30

      - name: Terraform Destroy
        working-directory: ./terraform
        run: |
           terraform destroy -auto-approve